name: CI Football Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3. Installer dépendances
      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn flask joblib

      # 4. Exécuter le training
      - name: Run training
        run: |
          python train.py

      # 5. Vérifier les fichiers
      - name: Check files
        run: |
          test -f model_logistic.pkl
          test -f scaler.pkl
          test -f imputer.pkl
